[package]
name = "lox-rust"
version = "0.1.0"
edition = "2021"
authors = ["John Mumm <jtfmumm@gmail.com>"]

[dependencies.argparse]
version = "*"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
